blockchain-insights/blockchain-data-subnet

.gitignore
neurons/remote_config.py
neurons/validators/scoring.py
tests/validators/test_score_calculation.py
tests/validators/test_scorer.py

This Pull Requests covers:
-  Blockchain score based on importance and miner distribution
- Complete unittest coverage of scoring functions
- Modification of the recency score Exponentially weighted instead of linear
- Remove unused imports, typo, and small modification on the gitignore file

Scoring function 2.0

---

neurons/miners/ethereum/funds_flow/graph_creator.py
neurons/nodes/evm/ethereum/node.py

Build graph creator for Ethereum network regarding the block and transaction structures

feat: build graph creator for ethereum

---

neurons/miners/bitcoin/funds_flow/graph_search.py
neurons/miners/ethereum/funds_flow/graph_creator.py
neurons/miners/ethereum/funds_flow/graph_indexer.py
neurons/miners/ethereum/funds_flow/indexer.py
neurons/nodes/evm/ethereum/node.py

Build graph indexer for Ethereum with RPC provider

feat: create indexer for ethereum

---

neurons/storage.py

fix typo in get_miners_metadata

---

neurons/miners/bitcoin/funds_flow_v2/graph_indexer.py
neurons/nodes/bitcoin/node.py

- added BITCOIN_V2_TX_OUT_HASHMAP_PICKLES env variable
- created dummy index on :Transaction

added BITCOIN_V2_TX_OUT_HASHMAP_PICKLES env variable

---

neurons/miners/ethereum/funds_flow/graph_creator.py
neurons/miners/ethereum/funds_flow/graph_indexer.py
neurons/miners/ethereum/funds_flow/graph_search.py
neurons/miners/ethereum/funds_flow/indexer.py
neurons/nodes/evm/ethereum/node.py

_Add Basic GraphSearch Query for EVM ETH._

[FEAT] : Add Graph Search Query

---

neurons/miners/ethereum/funds_flow_v2/graph_creator.py
neurons/miners/ethereum/funds_flow_v2/graph_indexer.py
neurons/miners/ethereum/funds_flow_v2/graph_search.py
neurons/miners/ethereum/funds_flow_v2/indexer.py

_Fix graph search query and changed / cleaned up file structure regarding v2._

[FIX]: Graph Search Query & V2 structure

---

neurons/miners/bitcoin/funds_flow/graph_search.py
neurons/miners/miner.py
neurons/utils.py

Added an implementation for running a read cypher query on a synapse
@aph5nt @0xMarx Let me know what the best way to test this would be

SN1-93 - Synapse query

---

neurons/validators/validator.py

Added an if not check to both block heights and k

SN-141 - Empty block heights bug (release 2.0)

---

neurons/miners/bitcoin/funds_flow/graph_indexer.py

https://linear.app/sn15/issue/SN1-161/null-address-bug-for-btc-block-831489
Handle null addresses and replace them with something else

SN-161 - handle addresses 

---

neurons/miners/miner.py
template/base/miner.py

SN1-228 - Minor adaptation to support "sync with latest template" 

---

.gitignore
neurons/miners/blacklist.py
neurons/remote_config.py
neurons/validators/validator.py

_This will ensure that the miners that be updated to 2.1 will keep their score during the migration by comparing synapse version and using is_grace_period field._

SN1-268 Add a logic to validator in order to mitigate smoothly from 2.0 to 2.1

---

neurons/validators/validator.py

this fix ensure that:
- invalid discovery reponse will be punish
- timeout, 404 reponse on validation will be punish

SN1-379 - fix crossvalidation

---

neurons/miners/tron/funds_flow/graph_creator.py
neurons/miners/tron/funds_flow/graph_indexer.py
neurons/miners/tron/funds_flow/graph_search.py
neurons/nodes/tron/node.py

_Scaffolding TronFundsFlow referring to ETH, BTC Node_
_Complete TronNode_

[FEAT]: SN1-225 BatchRequest & MinerScaffold

---

neurons/miners/blacklist.py
neurons/miners/miner.py
neurons/remote_config.py

Fix a small bug in query_blacklist function.

SN1-300 Handle non-voting valis in the query endpoint.

---

insights/api/insight_api.py
insights/api/schema/chat.py

_As a validator, receive user messages and return a miner's response._

SN1-504 Endpoint - POST /message

---

insights/api/schema/chat.py

https://linear.app/sn15/issue/SN1-702/change-validator-end-chat-request-schema-user-ids-to-uuids
Changed user ids to UUIDs to match chat-api user IDs.

[SN1-702] - Change validator-end chat request schema user ids to UUIDs

---

insights/api/insight_api.py
neurons/validators/validator.py

Add documentation to validator api endpoints.

SN1-681 Add missing documentation to validator api

---

insights/api/insight_api.py

add tags and description, set title to the api

hotfix for validator api swagger

---

insights/llm/base_llm.py
insights/llm/custom/__init__.py
insights/llm/openai/__init__.py
insights/llm/openai/graphchain.py
insights/llm/openai/memgraph_chain.py
insights/protocol.py
neurons/miners/miner.py

_Implement generic miner endpoint doing text2cypher query conversion._

SN1-422, SN1-594 Generic miner endpoint doing text-to-cypher-query LLM conversion

---

neurons/__init__.py
neurons/miners/bitcoin/funds_flow/graph_indexer.py
neurons/miners/bitcoin/funds_flow/indexer.py
neurons/miners/blacklist.py
neurons/miners/blacklist_registry.py
neurons/miners/ethereum/funds_flow/graph_indexer.py
neurons/miners/ethereum/funds_flow/indexer.py
neurons/miners/ip_blocker.py
neurons/miners/miner.py
neurons/nodes/bitcoin/node.py
neurons/nodes/evm/ethereum/node.py
neurons/remote_config.py
neurons/storage.py
neurons/validators/benchmark.py
neurons/validators/scoring.py
neurons/validators/uptime.py
neurons/validators/validator.py
template/api/get_query_axons.py
template/base/miner.py
template/base/neuron.py
template/base/validator.py
template/mock.py
template/validator/forward.py

sample miner output
`{"timestamp": "2024-05-19 10:47:08.019", "level": "INFO", "message": "\nno_prompt: false\nwallet:\n  name: miner\n  hotkey: default1\n  path: ~/.bittensor/wallets/\nsubtensor:\n  network: finney\n  chain_endpoint: ws://163.172.164.213:9944\n  _mock: false\nlogging:\n  debug: false\n  trace: false\n  record_log: false\n  logging_dir: ~/.bittensor/miners\naxon:\n  port: 8096\n  ip: '[::]'\n  external_port: null\n  external_ip: null\n  max_workers: 10\nnetuid: 1\nneuron:\n  device: cuda\n  epoch_length: 100\n  events_retention_size: 2 GB\n  dont_save_events: false\n  name: miner\n  full_path: /home/hyperbook/.bittensor/miners/miner/default1/netuid1/miner\nmock: false\nwandb:\n  'off': false\n  offline: false\n  notes: ''\n  project_name: template-miners\n  entity: …

added neuron module range default json logging
